### ISSUE TITLE
V3 Server Requests failing?

### ISSUE THREAD

**Issue by BuiltInParris** [JarvusInnovations/SeptaMobi#9]
I like version 3 a lot, big fan of what you guys have done with it. It seems like the requests to your internal server are coming back with a 500 error though. I would use this on my smartphone if it was working. I'm planning to build a personal app just for my route, if not.

**Comment by themightychris** [comment]
@BuiltInParris small fix to be compatible with a small update on SEPTA's end, should be good now, thanks for reporting!

**Comment by BuiltInParris** [comment]
@themightychris, just to be clear, are you saying it's fixed on the v3 website yet? Just wanted to make sure that wasn't your intention because I'm still seeing this. http://prntscr.com/9520w0

**Comment by themightychris** [comment]
Ooh no I only fixed it on the legacy septa.mobi site, had no idea anyone
was using v3. I'll take a look the call just needs to be changed from post
to get. It always should have been get but post used to work too
